export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER',
}

export enum MasterStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum PartnerType {
  LENDING_PARTNER = 'LENDING_PARTNER',
  LOAN_SOURCING_PARTNER = 'LOAN_SOURCING_PARTNER',
  DSA = 'DSA',
  FINTECH_PLATFORM = 'FINTECH_PLATFORM',
  MERCHANT = 'MERCHANT',
  EMPLOYER = 'EMPLOYER',
  COLLECTION_PARTNER = 'COLLECTION_PARTNER',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  CO_LENDING_PARTNER = 'CO_LENDING_PARTNER',
}

export enum ProductType {
  PERSONAL_LOAN = 'PERSONAL_LOAN',
  BUSINESS_LOAN = 'BUSINESS_LOAN',
  CONSUMER_DURABLE_LOAN = 'CONSUMER_DURABLE_LOAN',
  SALARY_ADVANCE = 'SALARY_ADVANCE',
  MERCHANT_CASH_ADVANCE = 'MERCHANT_CASH_ADVANCE',
  EDUCATION_LOAN = 'EDUCATION_LOAN',
  VEHICLE_LOAN = 'VEHICLE_LOAN',
  BNPL = 'BNPL',
  CREDIT_LINE = 'CREDIT_LINE',
  SECURED_LOAN = 'SECURED_LOAN',
}

export enum TenureUnit {
  DAYS = 'DAYS',
  WEEKS = 'WEEKS',
  MONTHS = 'MONTHS',
  YEARS = 'YEARS',
}

export enum RepaymentFrequency {
  MONTHLY = 'MONTHLY',
  WEEKLY = 'WEEKLY',
  FORTNIGHTLY = 'FORTNIGHTLY',
  QUARTERLY = 'QUARTERLY',
  CUSTOM = 'CUSTOM',
}

export enum InterestType {
  FIXED = 'FIXED',
  VARIABLE = 'VARIABLE',
}

export enum InterestCalculationMethod {
  FLAT = 'FLAT',
  REDUCING_BALANCE = 'REDUCING_BALANCE',
}

export enum FeeType {
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE',
  SLAB = 'SLAB',
}

export enum ApplicationFieldType {
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  CURRENCY = 'CURRENCY',
  DATE = 'DATE',
  SELECT = 'SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  CHECKBOX = 'CHECKBOX',
  RADIO = 'RADIO',
  FILE_UPLOAD = 'FILE_UPLOAD',
  ADDRESS = 'ADDRESS',
  BANK_DETAILS = 'BANK_DETAILS',
  EMPLOYMENT_DETAILS = 'EMPLOYMENT_DETAILS',
  BUSINESS_DETAILS = 'BUSINESS_DETAILS',
  GUARANTOR_DETAILS = 'GUARANTOR_DETAILS',
  CO_APPLICANT_DETAILS = 'CO_APPLICANT_DETAILS',
}

export enum ProviderType {
  ENACH = 'ENACH',
  ESIGN = 'ESIGN',
  KYC = 'KYC',
  BANK_VERIFICATION = 'BANK_VERIFICATION',
  CREDIT_BUREAU = 'CREDIT_BUREAU',
  PAYMENT_GATEWAY = 'PAYMENT_GATEWAY',
  DISBURSEMENT = 'DISBURSEMENT',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  DOCUMENT_STORAGE = 'DOCUMENT_STORAGE',
}

export enum EmploymentType {
  SALARIED = 'SALARIED',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  CONTRACT = 'CONTRACT',
  UNEMPLOYED = 'UNEMPLOYED',
}

export enum LoanApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  IN_REVIEW = 'IN_REVIEW',
  PENDING = 'PENDING',
  AUTO_REVIEWED = 'AUTO_REVIEWED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  KYC_PENDING = 'KYC_PENDING',
  KYC_IN_PROGRESS = 'KYC_IN_PROGRESS',
  KYC_COMPLETED = 'KYC_COMPLETED',
  DOCUMENT_PENDING = 'DOCUMENT_PENDING',
  DOCUMENT_VERIFICATION = 'DOCUMENT_VERIFICATION',
  BANK_VERIFICATION_PENDING = 'BANK_VERIFICATION_PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  CREDIT_APPROVED = 'CREDIT_APPROVED',
  CREDIT_REJECTED = 'CREDIT_REJECTED',
  AGREEMENT_PENDING = 'AGREEMENT_PENDING',
  AGREEMENT_GENERATED = 'AGREEMENT_GENERATED',
  ESIGN_PENDING = 'ESIGN_PENDING',
  ESIGN_COMPLETED = 'ESIGN_COMPLETED',
  ENACH_PENDING = 'ENACH_PENDING',
  ENACH_REGISTERED = 'ENACH_REGISTERED',
  ENACH_FAILED = 'ENACH_FAILED',
  READY_FOR_DISBURSEMENT = 'READY_FOR_DISBURSEMENT',
  DISBURSEMENT_PENDING = 'DISBURSEMENT_PENDING',
  DISBURSED = 'DISBURSED',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
  WRITTEN_OFF = 'WRITTEN_OFF',
}

export enum LoanStatus {
  PENDING = 'PENDING',
  AUTO_REVIEWED = 'AUTO_REVIEWED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DISBURSED = 'DISBURSED',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  DEFAULTED = 'DEFAULTED',
  WRITTEN_OFF = 'WRITTEN_OFF',
}

export enum DocumentTemplateStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum DocumentType {
  LOAN_AGREEMENT = 'LOAN_AGREEMENT',
  SANCTION_LETTER = 'SANCTION_LETTER',
  KEY_FACT_STATEMENT = 'KEY_FACT_STATEMENT',
  REPAYMENT_SCHEDULE = 'REPAYMENT_SCHEDULE',
  MANDATE_FORM = 'MANDATE_FORM',
  CONSENT_FORM = 'CONSENT_FORM',
  DISCLOSURE_DOCUMENT = 'DISCLOSURE_DOCUMENT',
  WELCOME_LETTER = 'WELCOME_LETTER',
  CLOSURE_LETTER = 'CLOSURE_LETTER',
  NOC = 'NOC',
}

export enum ConsentType {
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  CREDIT_BUREAU = 'CREDIT_BUREAU',
  KYC = 'KYC',
  DATA_SHARING = 'DATA_SHARING',
  ENACH = 'ENACH',
  ESIGN = 'ESIGN',
  LOAN_AGREEMENT_ACCEPTANCE = 'LOAN_AGREEMENT_ACCEPTANCE',
  MARKETING = 'MARKETING',
}

export enum ENachMandateStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING = 'PENDING',
  INITIATED = 'INITIATED',
  CUSTOMER_ACTION_PENDING = 'CUSTOMER_ACTION_PENDING',
  PROCESSING = 'PROCESSING',
  REGISTERED = 'REGISTERED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  SUSPENDED = 'SUSPENDED',
}

export enum ESignRequestStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING = 'PENDING',
  INITIATED = 'INITIATED',
  SIGNING_LINK_CREATED = 'SIGNING_LINK_CREATED',
  CUSTOMER_ACTION_PENDING = 'CUSTOMER_ACTION_PENDING',
  SIGNED = 'SIGNED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum DisbursementStatus {
  NOT_INITIATED = 'NOT_INITIATED',
  READY = 'READY',
  INITIATED = 'INITIATED',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
  CANCELLED = 'CANCELLED',
}

export enum RepaymentLedgerTransactionType {
  DISBURSEMENT = 'DISBURSEMENT',
  PRINCIPAL_DUE = 'PRINCIPAL_DUE',
  INTEREST_DUE = 'INTEREST_DUE',
  FEE_DUE = 'FEE_DUE',
  PENALTY_DUE = 'PENALTY_DUE',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_REVERSED = 'PAYMENT_REVERSED',
  FEE_WAIVED = 'FEE_WAIVED',
  PENALTY_WAIVED = 'PENALTY_WAIVED',
  WRITE_OFF = 'WRITE_OFF',
  REFUND = 'REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum ChargeType {
  PROCESSING_FEE = 'PROCESSING_FEE',
  DOCUMENTATION_FEE = 'DOCUMENTATION_FEE',
  CONVENIENCE_FEE = 'CONVENIENCE_FEE',
  INSURANCE = 'INSURANCE',
  STAMP_DUTY = 'STAMP_DUTY',
  GST = 'GST',
  LATE_FEE = 'LATE_FEE',
  PENAL_INTEREST = 'PENAL_INTEREST',
  BOUNCE_CHARGE = 'BOUNCE_CHARGE',
  FORECLOSURE_CHARGE = 'FORECLOSURE_CHARGE',
  PART_PAYMENT_CHARGE = 'PART_PAYMENT_CHARGE',
  OTHER = 'OTHER',
}

export enum RepaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
}

export enum PaymentCollectionStatus {
  INITIATED = 'INITIATED',
  LINK_CREATED = 'LINK_CREATED',
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum NotificationType {
  APPLICATION_DRAFTED = 'APPLICATION_DRAFTED',
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  APPLICATION_REVIEW_STARTED = 'APPLICATION_REVIEW_STARTED',
  LOAN_APPROVED = 'LOAN_APPROVED',
  LOAN_REJECTED = 'LOAN_REJECTED',
  PAYMENT_DUE = 'PAYMENT_DUE',
  PAYMENT_OVERDUE = 'PAYMENT_OVERDUE',
  REPAYMENT_RECEIVED = 'REPAYMENT_RECEIVED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  STATUS_CHANGE = 'STATUS_CHANGE',
}
